# Conclusion

## Main Takeaways

In this project, we fathom the economy impact of COVID-19. From a global scale, the economy recessed during the pandemic, namely in the year of 2020. When the World Health Organization declared the COVID-19 outbreak a pandemic, investors sense the possibility of economy recession and invested more low-risk assets. 

COVID-19 first outbroke in Wuhan, Hubei province, and spread to its neighbor provinces. We focused on the different economy impacts on different provinces in China. The pandemic had negative impacts to the national GDP: most provinces experienced negative GDP growth rate in the year of 2020, which was rare in history. The Midwest provinces had more sever economy drawback during the pandemic. Hubei, where COVID-19 first outbroke, had the most sever economy recession. The difference may be caused by the different locations, industrial structures, and lockdown policies. The western provinces tended to have more restrictive lockdown policies, and their economies were more dependent on trade in resources and raw materials. Western and central China suffered the greatest losses in terms of transportation and retail sales, especially Hubei and Xinjiang. Provinces close to the border have seen a drop in imports and exports, especially Tibet and Yunnan. From 2019 to 2020, the rate of unemployment growth in most provinces was positive. We can only see declines in a few western and central provinces.

## Limitation and Future Directions

The analysis in this project in primarily exploratory. For further research, we could inspect more on the reasons of differences in economy performances across provinces. For example, we could research more closely on the factors affecting province overall economy performance. We could show the weight of each sector in the GDP for each province and quantify the level of restrictiveness of lockdown policy for each province. We could build machine learning models on these factors and analysis the constitution of GDP performance quantitatively.  

## Lessons Learned

In this project, we learned to search for data from more reliable resources, and to validate the accuracy our data by random search. What's more, we learned that when we are processing Chinese characters, we should put extra focus on GBK encoding and utf-8 encoding.