lib--- 
title: "Impact of COVID-19"
author: "Runnan Jiang, Wanling Bai, Yancheng Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Recent years have witnessed the significant impact of COVID-19. Discovered in December 2019, COVID-19 quickly spread throughout the world. In March 2020, The World Health Organization declared the COVID-19 outbreak as a pandemic. It was not until December 2020 that effective vaccines were discovered. By now, COVID-19 has more than 635 million cases and more than 6 million deaths. Counties seal borders; people wear masks; school and works go virtually. As the epidemic continued, the economy started to recess: companies became bankrupted, and people struggled with continued unemployment. Though countries respond to the pandemic differently, most countries commit huge losses. The global economy suffers during and after the pandemic. 

The pandemic dramatically changes daily life and global dynamics. We are curious about the global and local impact of COVID-19. What is the worldwide impact of COVID-19? How do the regional impacts of COVID-19 differ from region to region? What are the potential reasons for the difference? We focus on the impact of COVID-19 in China. China has a large discrepancy in economic development across regions (East, Middle, West). The eastern region includes cities such as Shanghai, Hangzhou, Shandong and etc. They are relatively closer to the ports on the east coast, and trade makes a huge contribution to the economy. However, central and western regions of China relies heavily on natural resources, such as coal, copper, rare earths, and animal husbandry. In addition, the eastern region of China is mostly plain, livable, and has a large population, and keep attracting a large number of outstanding elites every year, while the western region is mostly plateau, sparsely populated, and the lack of talents also leads to low-tech industries and low labor costs. Also, their infrastructure and medical resource in Middle and West region is lagging behind. We are curious about whether the COVID's impact to China's economics is different across regions, and we will probe the interactions between regions of China during the pandemic. We will only use provinces in mainland China (excludes Taiwan, Hongkong, Macao) for policy consistency, and our research target is mainly focus on economic aspect.


Reference: https://en.wikipedia.org/wiki/Timeline_of_the_COVID-19_pandemic
