# Interactive component

<meta charset="utf-8">
<title>GroupFinalWork></title>
<style type="text/css">
   h1 {color:black;}  /* CSS styling */
   p {color:blue;}
</style>
<body>
<!-- Load d3.js -->
<script src="https://d3js.org/d3.v7.js"></script>
<h1>GDP (trillion dollar) by Country </h1>
 </h3>
<!-- Add buttons -->
<button onclick="update(data1)">2018 </button>
<button onclick="update(data2)">2019 </button>
<button onclick="update(data3)">2020 </button>
<button onclick="update(data4)">2021 </button>


<!-- Create a div where the graph will take place -->
<div id="d3try" ></div>
<script>
// create  data_set
var data1 = [ 
   {Category: "USA", value: 20.52},
   {Category: "CHN", value: 13.89},
   {Category: "JPN", value: 5.04},
   {Category: "DEU", value: 3.98},
   {Category: "GBR", value: 2.90},
];

var data2 = [
   {Category: "USA", value: 21.37},
   {Category: "CHN", value: 14.28},
   {Category: "JPN", value: 5.12},
   {Category: "DEU", value: 3.89},
   {Category: "GBR", value: 2.88},
];

var data3 = [
   {Category: "USA", value: 20.89},
   {Category: "CHN", value: 14.69},
   {Category: "JPN", value: 5.04},
   {Category: "DEU", value: 3.85},
   {Category: "GBR", value: 2.76},
   ];

var data4 = [
   {Category: "USA", value: 23.00},
   {Category: "CHN", value: 17.74},
   {Category: "JPN", value: 4.94},
   {Category: "DEU", value: 4.22},
   {Category: "GBR", value: 3.19},
   ];



// set the dimensions and margins of the graph
var margin = {top: 30, right: 10, bottom: 70, left: 60},
    width = 800 - margin.left - margin.right,
    height = 450 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#d3try")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")")
   .append("g", id ='circ');
  
// Initialize the X axis
var x = d3.scaleBand()
  .range([ 0, width ])
  .padding(0.2);
var xAxis = svg.append("g")
  .attr("transform", "translate(0," + height + ")")

// Initialize the Y axis
var y = d3.scaleLinear()
  .range([ height, 0]);
var yAxis = svg.append("g")
  .attr("class", "myYaxis")

// A function that create / update the plot for a given variable:
function update(data) {

  // Update the X axis
  x.domain(data.map(function(d) { return d.Category; }))
  xAxis.call(d3.axisBottom(x))

  // Update the Y axis
  y.domain([0, 25]);
  yAxis.transition().duration(1000).call(d3.axisLeft(y));

  // Create the u variable
  var u = svg.selectAll("rect")
    .data(data)

  u
    .enter()
    .append("rect") // Add a new rect for each new elements
    .merge(u) // get the already existing elements as well
    .transition() // and apply changes to all of them
    .duration(1000)
      .attr("x", function(d) { return x(d.Category); })
      .attr("y", function(d) { return y(d.value); })
      .attr("width", x.bandwidth())
      .attr("height", function(d) { return height - y(d.value); })
      .attr("fill", "#7b6888")

var rect=svg.selectAll("rect").on("mouseover", function() {
               //highlight
                 d3.select(this).style("fill","#2531ba");
                })
            .on("mouseout", function(d) {
                 d3.select(this).style("fill","#7b6888");
                });

  // If less group in the new dataset, I delete the ones not in use anymore
  u
    .exit()
    .remove()
    
      
    
}
update(data1)


</script>
</body>


In this chart, we show GDP (trillion dollar) for the top five countries from 2018 to 2021. By clicking on one of the buttons on top left of the graph, users can view the data of one of those years. When a different button is clicked, the transition of bars takes 1 second, so users can see how GDP of United States, China, Japan, United Kingdom, Germany change between two years. When the mouse hovers over a bar, the bar’s color changes from purple to blue, which makes it more eye-catching and distinguishes it from other columns.