# Proposal

## Research topic
Our research mainly focuses on the impact of COVID-19 on Chinese and global economy. After the outbreak in 2020, COVID-19 pandemic has had many adverse effects on the economy. We want to explore countries' economic status before and during COVID-19 using indexes as follows. 

## Data availability

For the Covid-19 data, we download data from Harvard Dataverse (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/MR5IJN). It contains 15 files including China Basemap,cityConfirmed, cityDeath,  cityRecover and all those time-series data are at provincial level. It would be a good dataset for us to analyze China's pandemic trend and severity stages across time. We also compared this data set with data from Google Covid-19 open data (https://health.google.com/covid-19/open-data/raw-data) and World Health Organization (https://covid19.who.int/data). We prefer dataset from Harvard because it includes provincial data, but we will still use WHO's data for a brief overlook at the global level.

For the provincial time-series economics data in China, we download data from China National Bureau of Statistics (https://data.stats.gov.cn/easyquery.htm?cn=G0104), which includes provincial GDP, Transportation Increment, Retailing Increment, Registered unemployment, Provincial Export, Provincial Import and etc. CNBS is the dataset built by the government and is considered as the most authoritative data for China, and we will use this dataset to measure economics overlook, supply-chain cost, offline store's operation, unemployment and China's trading account. We downloaded the USD index from Investing.com. The data from Investing is consistent with data from Bloomberg, but it's free for students outside Business School. For analysis of COVID-19's impact to USD index, we use time series data that range from 2018.10.31 to 2022.10.31. We choose this data because USD index is a good measure of investor's panic index from the Economist's perspective, for USD is considered as the safest asset in the world and investors tend to buy USD when the probability of recession increases.

All of our data are in csv or excel format. The data downloaded from CNBS is in a good stage, with no missing values and is in panel data format. However, China's COVID-19 data downloaded from Harvard Dataverse is sparse and has some missing values. If the data have problem, we can contact the owner of dataset throught the "Contact" button provided by the website. The good thing is, lots of scholars are using this database for research right now, and their citation and dataset's related publication is tractable. We can also contact them if we need further academic discussion.